apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: staging
type: Opaque
stringData:
  jwt-secret: your-jwt-secret-here
  mongodb-uri: mongodb+srv://username:password@cluster.mongodb.net/tour-travel-db
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: production
type: Opaque
stringData:
  jwt-secret: your-production-jwt-secret-here
  mongodb-uri: mongodb+srv://username:password@cluster.mongodb.net/tour-travel-db
